name: Synchronise Translations

on:
  workflow_dispatch:

jobs:
  langsync:
    name: Synchronise UI languages in transifex
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install https://github.com/Philip-Larsen-Donnelly/translayer/archive/refs/tags/v0.0.7.zip


    - name: Run the script
      run: python ./ui_language_spreader.py
      env:
        TX_TOKEN: ${{ secrets.DHIS2_APPS_TX_TOKEN }}

