name: Transifex App Sync - Weekly

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '41 22 * * 6'
  workflow_dispatch:

jobs:

  build:
    name: Synchronise translations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
      shell: bash

    - name: install hub
      run: |
        hub_version="2.14.2"
        hub_filename="hub-linux-amd64-${hub_version}"
        downloadUrl="https://github.com/mislav/hub/releases/download/v${hub_version}/${hub_filename}.tgz"
        curl -fsSL ${downloadUrl} -o /tmp/${hub_filename}.tgz
        tar xzf /tmp/${hub_filename}.tgz -C /tmp/
        sudo mv /tmp/${hub_filename}/bin/hub /usr/local/bin
        hub --version
      shell: bash

    - name: Run the script
      run: ./transyncosaurus_ALL.sh
      shell: bash
      env:
        TXTOKEN: ${{ secrets.DHIS2_APPS_TX_TOKEN }}
        GITHUB_USER: ${{ secrets.DHIS2_GITHUB_USER }}
        GITHUB_PASSWORD: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
        TRANSIFEX_SYNC_TAG: jenkins-weekly-app-sync
