name: Transifex App Sync - Single

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install transifex-client

    - name: Run the script
      run: ./transyncosaurus_SINGLE.sh
      shell: bash
      env:
        TXTOKEN: ${{ secrets.DHIS2_APPS_TX_TOKEN }}
        GITHUB_USER: ${{ secrets.DHIS2_GITHUB_USER }}
        GITHUB_PASSWORD: ${{ secrets.DHIS2_GITHUB_PASSWORD }}
