name: Transifex App Sync - Single

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
      shell: bash

    - name: Run the script
      run: ./transyncosaurus_SINGLE.sh
      env:
        TXTOKEN: ${{ secrets.DHIS2_APPS_TX_TOKEN }}
        GITHUB_USER: ${{ secrets.DHIS2_GITHUB_USER }}
        GITHUB_PASSWORD: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
